---
- name: Testing FHRP Deployment
  connection: network_cli
  gather_facts: False
  hosts: network
  tasks:
    - name: Save generated configuration
      template:
        src: templates/fhrp.j2
        dest: templates/{{ inventory_hostname}}.conf

...